version: '4.34.2'
services:
  mysql_sesas:
    env_file:
      - .env
    container_name: mysql_sesas
    hostname: mysql_sesas
    image: mysql:8
    restart: always
    command:
      - --mysql-native-password=ON
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb_force_recovery=0
    volumes:
      - ./mysql_sesas:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      TZ: America/Sao_Paulo